"""empty message

Revision ID: 218585cec5f6
Revises: 811b861c4ff4
Create Date: 2020-03-14 15:07:49.587725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218585cec5f6'
down_revision = '811b861c4ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Map', sa.Column('background', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Map', 'background')
    # ### end Alembic commands ###
