"""empty message

Revision ID: 46c1f1ada6e5
Revises: 
Create Date: 2020-03-01 17:02:00.259623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c1f1ada6e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Character_Active_Abilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('ability_type', sa.String(length=45), nullable=True),
    sa.Column('ability_amount', sa.Integer(), nullable=True),
    sa.Column('ability_duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Character_Passive_Abilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('passive_ability_type', sa.String(length=45), nullable=True),
    sa.Column('passive_ability_amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('current_score', sa.Integer(), nullable=True),
    sa.Column('current_money', sa.Integer(), nullable=True),
    sa.Column('current_xp', sa.Integer(), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('character_active_ability_id', sa.Integer(), nullable=True),
    sa.Column('character_passive_abilities_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_active_ability_id'], ['Character_Active_Abilities.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['character_passive_abilities_id'], ['Character_Passive_Abilities.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('Character_Passive_Abilities')
    op.drop_table('Character_Active_Abilities')
    # ### end Alembic commands ###
