"""empty message

Revision ID: 811b861c4ff4
Revises: a889353f0208
Create Date: 2020-03-11 20:23:00.108891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811b861c4ff4'
down_revision = 'a889353f0208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('modifier1Name', sa.String(length=255), nullable=True),
    sa.Column('modifier1Amount', sa.Integer(), nullable=True),
    sa.Column('modifier2Name', sa.String(length=255), nullable=True),
    sa.Column('modifier2Amount', sa.Integer(), nullable=True),
    sa.Column('modifier3Name', sa.String(length=255), nullable=True),
    sa.Column('modifier3Amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Map')
    # ### end Alembic commands ###
